apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
  namespace: dev
spec:
  type: ExternalName
  externalName: host.minikube.internal
  ports:
    - name: port
      port: 3306
  selector:
    app: tables
