insert into customers (first_name, table_number, cash, address)
VALUES ('alice', 1, 12.34, '123 main st');
insert into customers (first_name, table_number, cash, address)
VALUES ('bob', 3, 2.34, '124 main st');
insert into customers (first_name, table_number, cash, address)
VALUES ('chuck', 3, 5.00, '125 main st');
insert into customers (first_name, table_number, cash, address)
VALUES ('dave', 1, 100.00, '126 main st');
insert into customers (first_name, table_number, cash, address)
VALUES ('ed', 2, 1.23, '127 main st');